- name: Run Odoo tests (Docker)
  run: |
    docker run --rm \
      --network host \
      -v "${{ github.workspace }}:/mnt/extra-addons" \
      odoo:19 \
      --addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons \
      -d odoo \
      --db_host=127.0.0.1 \
      --db_port=5432 \
      --db_user=odoo \
      --db_password=odoo \
      -i plasticos_documents,plasticos_commission,plasticos_logistics,plasticos_transaction \
      --without-demo=all \
      --test-enable \
      --log-level=info \
      --stop-after-init
